const languages = [
	{ id: 1, language: 'English', code: 'en' },
	{ id: 2, language: 'Spanish', code: 'es' },
	{ id: 3, language: 'French', code: 'fr' },
	{ id: 4, language: 'Russian', code: 'ru' },
	{ id: 5, language: 'German', code: 'de' },
	{ id: 6, language: 'Italian', code: 'it' },
	{ id: 7, language: 'Portuguese', code: 'pt' },
	{ id: 8, language: 'Chinese (Simplified)', code: 'zh-CN' },
	{ id: 9, language: 'Chinese (Traditional)', code: 'zh-TW' },
	{ id: 10, language: 'Japanese', code: 'ja' },
	{ id: 11, language: 'Korean', code: 'ko' },
	{ id: 12, language: 'Dutch', code: 'nl' },
	{ id: 13, language: 'Greek', code: 'el' },
	{ id: 14, language: 'Arabic', code: 'ar' },
	{ id: 15, language: 'Hindi', code: 'hi' },
	{ id: 16, language: 'Swedish', code: 'sv' },
	{ id: 17, language: 'Turkish', code: 'tr' },
	{ id: 18, language: 'Polish', code: 'pl' },
	{ id: 19, language: 'Czech', code: 'cs' },
	{ id: 20, language: 'Hungarian', code: 'hu' },
	{ id: 21, language: 'Thai', code: 'th' },
	{ id: 22, language: 'Vietnamese', code: 'vi' },
	{ id: 23, language: 'Danish', code: 'da' },
	{ id: 24, language: 'Finnish', code: 'fi' },
	{ id: 25, language: 'Norwegian', code: 'no' },
	{ id: 26, language: 'Hebrew', code: 'he' },
	{ id: 27, language: 'Indonesian', code: 'id' },
	{ id: 28, language: 'Malay', code: 'ms' },
	{ id: 29, language: 'Slovak', code: 'sk' },
	{ id: 30, language: 'Ukrainian', code: 'uk' },
	{ id: 31, language: 'Bulgarian', code: 'bg' },
	{ id: 32, language: 'Romanian', code: 'ro' },
	{ id: 33, language: 'Lithuanian', code: 'lt' },
	{ id: 34, language: 'Latvian', code: 'lv' },
	{ id: 35, language: 'Estonian', code: 'et' },
	{ id: 36, language: 'Croatian', code: 'hr' },
	{ id: 37, language: 'Serbian', code: 'sr' },
	{ id: 38, language: 'Slovenian', code: 'sl' },
	{ id: 39, language: 'Filipino', code: 'tl' },
	{ id: 40, language: 'Persian', code: 'fa' },
	{ id: 41, language: 'Select Language', code: 'auto' }
];

export default languages;