const languages = [
	{ id: 1, language: 'English', code: 'en-US' },
	{ id: 2, language: 'Spanish', code: 'es-ES' },
	{ id: 3, language: 'French', code: 'fr-FR' },
	{ id: 4, language: 'Russian', code: 'ru-RU' },
	{ id: 5, language: 'German', code: 'de-DE' },
	{ id: 6, language: 'Italian', code: 'it-IT' },
	{ id: 7, language: 'Portuguese', code: 'pt-PT' },
	{ id: 8, language: 'Chinese (Simplified)', code: 'zh-CN' },
	{ id: 9, language: 'Chinese (Traditional)', code: 'zh-TW' },
	{ id: 10, language: 'Japanese', code: 'ja-JP' },
	{ id: 11, language: 'Korean', code: 'ko-KR' },
	{ id: 12, language: 'Dutch', code: 'nl-NL' },
	{ id: 13, language: 'Greek', code: 'el-GR' },
	{ id: 14, language: 'Arabic', code: 'ar-SA' },
	{ id: 15, language: 'Hindi', code: 'hi-IN' },
	{ id: 16, language: 'Swedish', code: 'sv-SE' },
	{ id: 17, language: 'Turkish', code: 'tr-TR' },
	{ id: 18, language: 'Polish', code: 'pl-PL' },
	{ id: 19, language: 'Czech', code: 'cs-CZ' },
	{ id: 20, language: 'Hungarian', code: 'hu-HU' },
	{ id: 21, language: 'Thai', code: 'th-TH' },
	{ id: 22, language: 'Vietnamese', code: 'vi-VN' },
	{ id: 23, language: 'Danish', code: 'da-DK' },
	{ id: 24, language: 'Finnish', code: 'fi-FI' },
	{ id: 25, language: 'Norwegian', code: 'no-NO' },
	{ id: 26, language: 'Hebrew', code: 'he-IL' },
	{ id: 27, language: 'Indonesian', code: 'id-ID' },
	{ id: 28, language: 'Malay', code: 'ms-MY' },
	{ id: 29, language: 'Slovak', code: 'sk-SK' },
	{ id: 30, language: 'Ukrainian', code: 'uk-UA' },
	{ id: 31, language: 'Bulgarian', code: 'bg-BG' },
	{ id: 32, language: 'Romanian', code: 'ro-RO' },
	{ id: 33, language: 'Lithuanian', code: 'lt-LT' },
	{ id: 34, language: 'Latvian', code: 'lv-LV' },
	{ id: 35, language: 'Estonian', code: 'et-EE' },
	{ id: 36, language: 'Croatian', code: 'hr-HR' },
	{ id: 37, language: 'Serbian', code: 'sr-RS' },
	{ id: 38, language: 'Slovenian', code: 'sl-SI' },
	{ id: 39, language: 'Filipino', code: 'tl-PH' },
	{ id: 40, language: 'Persian', code: 'fa-IR' },
	{ id: 41, language: 'Select Language', code: 'Autodetect' }
];

export default languages;